package rtw.entity.gererAvis.avisGlobal.avisGlobalAgence.entity;

import rtw.entity.gererAvis.avisGlobal.entity.AvisGlobal;
import rtw.entity.gererAvis.avisGlobal.interfaces.IAvisGlobal;


/**
 * Entity {@link AvisGlobalAgence} class fille de {@link AvisGlobal} contient la moyen des notes des avis utilisateur sur une agence.
 * 
 * @author Aurélien
 * @version 1
 * @since 13/03/2017
 *
 */
public class AvisGlobalAgence extends AvisGlobal implements IAvisGlobal{

	/**
	 * TODO
	 * Serial generated by default regenerate it when class complete 
	 */
	private static final long serialVersionUID = 1L;

	
}
