package rtw.entity.gererAvis.commentaire.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

import rtw.entity.gererAvis.commentaire.interfaces.ICommentaire;

/**
 * Entity {@link Commentaire} contient le commentaire de l'utilisateur.
 * 
 * @author Aurélien
 * @version 1
 * @since 13/03/2017
 *
 */
@Entity
public class Commentaire implements ICommentaire,Serializable {

	/**
	 * TODO
	 * Serial generated by default regenerate it when class complete 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	private String idCommentaire;
	@Column(length=4000,nullable=false)
	private String contenu;
	/**
	 * @return the idCommentaire
	 */
	public String getIdCommentaire() {
		return idCommentaire;
	}
	/**
	 * @param idCommentaire the idCommentaire to set
	 */
	public void setIdCommentaire(String idCommentaire) {
		this.idCommentaire = idCommentaire;
	}
	/**
	 * @return the contenu
	 */
	public String getContenu() {
		return contenu;
	}
	/**
	 * @param contenu the contenu to set
	 */
	public void setContenu(String contenu) {
		this.contenu = contenu;
	}
	
}
