package rtw.entity.gererAvis.commentaire.entity;

import java.io.Serializable;

import javax.persistence.Column;

import rtw.entity.gererAvis.commentaire.interfaces.ICommentaire;

/**
 * Entity {@link Commentaire} contient le commentaire de l'utilisateur.
 * 
 * @author Aurélien
 * @version 1
 * @since 13/03/2017
 *
 */
public class Commentaire implements ICommentaire,Serializable {

	/**
	 * TODO
	 * Serial generated by default regenerate it when class complete 
	 */
	private static final long serialVersionUID = 1L;
	
	@Column(length=4000,nullable=false)
	private String contenu;
	
}
