package rtw.entity.gererAvis.avisGlobal.avisGlobalAnnonce.entity;

import rtw.entity.gererAvis.avisGlobal.avisGlobalAnnonce.interfaces.IAvisGlobalAnnonce;
import rtw.entity.gererAvis.avisGlobal.entity.AvisGlobal;

/**
 * Entity {@link AvisGlobalAnnonce} class fille de {@link AvisGlobal} contient la moyen des notes des avis utilisateur sur une annonce.
 * 
 * @author Aurélien
 * @version 1
 * @since 13/03/2017
 *
 */
public class AvisGlobalAnnonce extends AvisGlobal implements IAvisGlobalAnnonce {

	/**
	 * TODO
	 * Serial generated by default regenerate it when class complete 
	 */
	private static final long serialVersionUID = 1L;

	
}
