package rtw.entity.gererAvis.note.entity;

import java.io.Serializable;

import rtw.entity.gererAvis.note.interfaces.INotes;

/**
 * TODO
 * @author Afpa
 *
 */
public class Notes implements INotes,Serializable{

	/**
	 * TODO
	 * Serial generated by default regenerate it when class complete 
	 */
	private static final long serialVersionUID = 1L;


}
