package rtw.entity.gererAvis.note.entity;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.MappedSuperclass;

import org.jboss.resteasy.spi.touri.MappedBy;

import rtw.entity.gererAvis.note.interfaces.INotes;


/**
 * Entity {@link Note} class mere abstraite de TODO
 * 
 * @author Aurélien
 * @version 1
 * @since 15/03/2017
 *
 */
@Entity
@Inheritance(strategy=InheritanceType.SINGLE_TABLE)
public abstract class Note implements INotes,Serializable {
	
	/**
	 * TODO
	 * Serial generated by default regenerate it when class complete 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	private String idNote;
	private int valeur;

	
	public int getValeur() {
		return valeur;
	}

	public void setValeur(int valeur) {
		this.valeur = valeur;
	}

}
